package com.team5.on_stage.global.constants;

public enum Platform {
    NULL, TIKTOK, INSTAGRAM, FACEBOOK, NOTION, X, SPOTIFY, YOUTUBE, SOUNDCLOUD, APPLE_MUSIC, TWITCH, CHZZK, GITHUB, YOUTUBE_MUSIC, TISTORY, VELOG, GITLAB, ;
}
